version: "3.8"

networks:
    course-compose:
    kafka:

services:
    # ================================
    # Postgres Database
    postgres:
        image: postgres
        container_name: coursecompose_db
        environment:
            POSTGRES_DB: coursecompose-dev
            POSTGRES_USER: syntax
            POSTGRES_PASSWORD: stamford
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"
        networks:
            - course-compose

    prisma-bootstrap:
        build:
            context: .
            dockerfile: ./Dockerfile.dev
            args:
                DATABASE_URL: "postgres://syntax:stamford@postgres:5432/coursecompose-dev"
                PRISMA_PROVIDER: "prisma-client-js"
                PRISMA_OUTPUT: "/app/node_modules/.prisma/client"
        depends_on:
            - postgres
        networks:
            - course-compose

    # ================================
    # Kafka Message Queue
    zookeeper:
        image: confluentinc/cp-zookeeper
        restart: unless-stopped
        container_name: kafka_zookeeper
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - kafka

    broker: # broker = server running kafka instance
        image: confluentinc/cp-kafka
        restart: unless-stopped
        container_name: kafka_broker
        ports:
            - "9092:9092"
        depends_on:
            - zookeeper
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, PLAINTEXT_INTERNAL:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        networks:
            - kafka
