version: "3.8"

networks:
    reviews-test:

services:
    postgres-integration:
        image: postgres
        container_name: coursecompose_db_integration
        environment:
            POSTGRES_DB: coursecompose-integration
            POSTGRES_USER: syntax
            POSTGRES_PASSWORD: stamford
        volumes:
            - ./review/data/datasource/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            - reviews-test

    integration-test:
        build:
            context: ../../
            dockerfile: apps/reviews-api/Dockerfile.integration
        environment:
            - DATABASE_URL=postgres://syntax:stamford@postgres-integration:5432/coursecompose-integration
            - PRISMA_PROVIDER=go run github.com/steebchen/prisma-client-go
            - PRISMA_OUTPUT=/review-app-integration/review/data/datasource/db
            - JWT_SECRET=test-jwt-token
        depends_on:
            - postgres-integration
        networks:
            - reviews-test
