version: "3.8"

services:
    khing:
        build:
            context: ../../
            dockerfile: apps/course-api/Dockerfile
        ports:
          - 8002:8002
        environment:
            DATABASE_URL: postgres://syntax:stamford@host.docker.internal:5432/coursecompose-dev
