name: Pipeline for testing

on:
    pull_request:

jobs:
    test:
        name: Course compose CI/CD testing
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4
              with:
                  run_install: false

            - name: Install turbo
              run: pnpm install --global turbo@1.13.4

            - name: Install jest
              working-directory: ./apps/course-api
              run: pnpm add --save-dev jest @types/jest ts-jest

            - name: Setup Go 1.21.5
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.5"

            - name: Generate Go ORM
              working-directory: ./apps/reviews-api
              run: pnpm run bootstrap:unix # triggers only in reviews-api

            - name: Unit test
              run: pnpm run unit

            - name: Test
              run: pnpm run test

            - name: Integration test
              run: pnpm run integration
