name: Pipeline for testing

on:
    pull_request:

jobs:
    test:
        name: Course compose CI/CD testing
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            PRISMA_PROVIDER: go run github.com/steebchen/prisma-client-go
            PRISMA_OUTPUT: ../../apps/prisma/db

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v2.2.2
              with:
                  version: 8
                  run_install: false

            - name: Install turbo
              run: pnpm install --global turbo

            - name: Install jest
              working-directory: ./apps/course-api
              run: pnpm add --save-dev jest @types/jest ts-jest

            - name: Setup Go 1.21.5
              uses: actions/setup-go@v4
              with:
                  go-version: "1.21.5"

            - name: Generate ORM
              working-directory: ./apps/reviews-api
              run: go run github.com/steebchen/prisma-client-go generate --schema=../../packages/prisma/schema.prisma

            - name: Unit test
              run: pnpm run unit

            - name: Integration test
              run: pnpm run integration

            - name: Test
              run: pnpm run test
